on:
  deployment_status
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }}
    steps:
      - run: echo ${{ github.event.deployment_status.target_url }}
      - run: echo 'test'
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: get deploy
        run: |
          echo ${{ vars.TEST }}
