on:
  deployment_status
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.deployment_status.target_url }}
      - run: echo 'test'
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: get deploy
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ywatanabe-dev/nextjs-test/deployments/${{ github.event.deployment.id }}

      - name: api call
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ywatanabe-dev/nextjs-test/git/ref/heads/main
